version: '3.1'

volumes:
  postgresql_data:

services:
#  server:
#    container_name: server
#    build:
#      context: .
#      dockerfile: ./server/Dockerfile
#    ports:
#      - "7001:7001"
#    depends_on:
#      db:
#        condition: service_healthy
#        restart: true

  db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 20s
      retries: 10
      start_period: 5s
